### ISSUE TITLE
Jmeter not able to load JSR223Sampler and related with jmeter-influxdb2-listener-plugin

### ISSUE THREAD

**Issue by caozhong** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#99]
the jmeter scripts works well with meter 5.6, until jmeter-influxdb2-listener-plugin placed under jmeter lib/ext, then loading the scripts fails, with pop up error message during loading: Error org.apache.jmeter.util.JSR223BeanInfoSupport.

with jmeter-influxdb2-listener-plugin, load ing scripts works only when all JSR223Sampler in the scripts deleted.

**Comment by caozhong** [comment]
The error: 2024-01-30 10:45:38,566 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[#79,CoreBiz_360Review 1-1,6,main] java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.runtime.InvokerHelper 	at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:46) ~[groovy-3.0.20.jar:3.0.20] 	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32) ~[groovy-3.0.20.jar:3.0.20] 	at groovy.lang.Binding.<init>(Binding.java:36) ~[groovy-3.0.20.jar:3.0.20] 	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl$2.<init>(GroovyScriptEngineImpl.java:222) ~[groovy-jsr223-3.0.20.jar:3.0.20] 	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:222) ~[groovy-jsr223-3.0.20.jar:3.0.20] 	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155) ~[groovy-jsr223-3.0.20.jar:3.0.20] 	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231) ~[java.scripting:?] 	at org.apache.jmeter.functions.Groovy.execute(Groovy.java:123) ~[ApacheJMeter_functions.jar:5.6.3] 	at org.apache.jmeter.engine.util.CompoundVariable.execute(CompoundVariable.java:139) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.engine.util.CompoundVariable.execute(CompoundVariable.java:114) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.testelement.property.FunctionProperty.getStringValue(FunctionProperty.java:104) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.testelement.TestElement.get(TestElement.kt:276) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.IfController.getCondition(IfController.java:173) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.IfController.next(IfController.java:234) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.TransactionController.nextIsAController(TransactionController.java:180) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.GenericController.next(GenericController.java:185) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.TransactionController.nextWithTransactionSampler(TransactionController.java:165) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.TransactionController.next(TransactionController.java:137) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.GenericController.nextIsAController(GenericController.java:232) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.GenericController.next(GenericController.java:185) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.LoopController.next(LoopController.java:119) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.GenericController.nextIsAController(GenericController.java:232) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.GenericController.next(GenericController.java:185) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.LoopController.next(LoopController.java:119) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.GenericController.nextIsAController(GenericController.java:232) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.GenericController.next(GenericController.java:185) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.control.LoopController.next(LoopController.java:119) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:109) ~[ApacheJMeter_core.jar:5.6.3] 	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:303) ~[ApacheJMeter_core.jar:5.6.3] 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by caozhong** [comment]
jmeter 5.6.2 works while 5.6.3 lib has above issue

**Comment by Xebi4i** [comment]
The same. Can the author rebuild the .jar with the supporting 3.0.20 version of Groovy plugins instead of 3.0.17? It causes collapses. 
Thanks @mderevyankoaqa

**Comment by ShigellaShigella** [comment]
@caozhong It is interesting, because I have same issue with version 5.6.2 (I tried plugin version 2.5 and 2.8). 
I get the impression it is something with UI, because we use 5.6.2 version in the pipeline, when we run it from command line.  
@mderevyankoaqa if you could find a moment I would be really thankful, because your plugin helps me a lot!
